# Generated by Django 4.1.6 on 2023-03-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_likepost"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="password",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
