# Generated by Django 4.1.6 on 2023-03-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
