# Generated by Django 4.1.6 on 2023-03-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_profile_location_remove_profile_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LikePost",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
